server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
      context-path: /
      encoding:
        charset: UTF-8
        force-response: true
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307
#    username: root
#    password: 123456789
#  jpa:
#    hibernate:
#      ddl-auto: update